name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.5+1

  socket_io_client: ^3.1.3 # This version helps avoid many compatibility issues
  go_router: ^17.0.1
  http: ^1.1.0
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  http_parser: ^4.0.0
  image_picker: ^1.2.1
  record: ^6.2.0
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Using a current version range for lints
  flutter_lints: ^3.0.0
  http: ^1.2.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/logo.png"
